// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigDelete(arg1) {
  return window['go']['main']['App']['ConfigDelete'](arg1);
}

export function ConfigGetById(arg1) {
  return window['go']['main']['App']['ConfigGetById'](arg1);
}

export function ConfigGetByKey(arg1) {
  return window['go']['main']['App']['ConfigGetByKey'](arg1);
}

export function ConfigInsert(arg1) {
  return window['go']['main']['App']['ConfigInsert'](arg1);
}

export function ConfigUpdate(arg1) {
  return window['go']['main']['App']['ConfigUpdate'](arg1);
}

export function GoodsAll() {
  return window['go']['main']['App']['GoodsAll']();
}

export function GoodsDelete(arg1) {
  return window['go']['main']['App']['GoodsDelete'](arg1);
}

export function GoodsEdit(arg1) {
  return window['go']['main']['App']['GoodsEdit'](arg1);
}

export function GoodsGetById(arg1) {
  return window['go']['main']['App']['GoodsGetById'](arg1);
}

export function GoodsPage(arg1) {
  return window['go']['main']['App']['GoodsPage'](arg1);
}

export function GoodsSave(arg1) {
  return window['go']['main']['App']['GoodsSave'](arg1);
}

export function GoodsTypeDeleteByName(arg1) {
  return window['go']['main']['App']['GoodsTypeDeleteByName'](arg1);
}

export function GoodsTypeSave(arg1) {
  return window['go']['main']['App']['GoodsTypeSave'](arg1);
}

export function GoodsTypeSelectAll() {
  return window['go']['main']['App']['GoodsTypeSelectAll']();
}

export function GoodsTypeUpdate(arg1) {
  return window['go']['main']['App']['GoodsTypeUpdate'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function MemberAll() {
  return window['go']['main']['App']['MemberAll']();
}

export function MemberDeleteById(arg1) {
  return window['go']['main']['App']['MemberDeleteById'](arg1);
}

export function MemberGetById(arg1) {
  return window['go']['main']['App']['MemberGetById'](arg1);
}

export function MemberGetByPhone(arg1) {
  return window['go']['main']['App']['MemberGetByPhone'](arg1);
}

export function MemberLevelDeleteById(arg1) {
  return window['go']['main']['App']['MemberLevelDeleteById'](arg1);
}

export function MemberLevelSave(arg1) {
  return window['go']['main']['App']['MemberLevelSave'](arg1);
}

export function MemberLevelSelectAll() {
  return window['go']['main']['App']['MemberLevelSelectAll']();
}

export function MemberLevelUpdate(arg1) {
  return window['go']['main']['App']['MemberLevelUpdate'](arg1);
}

export function MemberPage(arg1) {
  return window['go']['main']['App']['MemberPage'](arg1);
}

export function MemberSave(arg1) {
  return window['go']['main']['App']['MemberSave'](arg1);
}

export function MemberUpdate(arg1) {
  return window['go']['main']['App']['MemberUpdate'](arg1);
}

export function Order(arg1) {
  return window['go']['main']['App']['Order'](arg1);
}

export function OrderPage(arg1) {
  return window['go']['main']['App']['OrderPage'](arg1);
}

export function OrderRecords(arg1) {
  return window['go']['main']['App']['OrderRecords'](arg1);
}

export function OrderStatistics(arg1) {
  return window['go']['main']['App']['OrderStatistics'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SystemBackup(arg1) {
  return window['go']['main']['App']['SystemBackup'](arg1);
}

export function SystemDesktopPath() {
  return window['go']['main']['App']['SystemDesktopPath']();
}

export function TaskDetailBatchInsert(arg1) {
  return window['go']['main']['App']['TaskDetailBatchInsert'](arg1);
}

export function TaskDetailDelete(arg1) {
  return window['go']['main']['App']['TaskDetailDelete'](arg1);
}

export function TaskDetailDeleteByTaskId(arg1) {
  return window['go']['main']['App']['TaskDetailDeleteByTaskId'](arg1);
}

export function TaskDetailGetByTask(arg1) {
  return window['go']['main']['App']['TaskDetailGetByTask'](arg1);
}

export function TaskDetailSave(arg1) {
  return window['go']['main']['App']['TaskDetailSave'](arg1);
}

export function TaskDetailUpdate(arg1) {
  return window['go']['main']['App']['TaskDetailUpdate'](arg1);
}

export function TaskUpdate(arg1) {
  return window['go']['main']['App']['TaskUpdate'](arg1);
}

export function TasksAll() {
  return window['go']['main']['App']['TasksAll']();
}

export function TasksDelete(arg1) {
  return window['go']['main']['App']['TasksDelete'](arg1);
}

export function TasksGetById(arg1) {
  return window['go']['main']['App']['TasksGetById'](arg1);
}

export function TasksPage(arg1) {
  return window['go']['main']['App']['TasksPage'](arg1);
}

export function TasksSave(arg1) {
  return window['go']['main']['App']['TasksSave'](arg1);
}

export function UserBatchInsert(arg1) {
  return window['go']['main']['App']['UserBatchInsert'](arg1);
}

export function UserDelete(arg1) {
  return window['go']['main']['App']['UserDelete'](arg1);
}

export function UserPage(arg1) {
  return window['go']['main']['App']['UserPage'](arg1);
}

export function UserSave(arg1) {
  return window['go']['main']['App']['UserSave'](arg1);
}

export function UserUpdate(arg1) {
  return window['go']['main']['App']['UserUpdate'](arg1);
}
